global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Fiap Projeto Games
  - job_name: 'fiap-projeto-games-api'
    static_configs:
      - targets: ['api:80']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # SQL Server (se necessário)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['db:1433']
    scrape_interval: 60s

  # Redis (se necessário)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 